# Generated by Django 3.2.10 on 2022-08-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=450)),
                ('location', models.CharField(max_length=45)),
                ('products', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=50)),
                ('IEAL', models.CharField(max_length=50)),
                ('heads', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bussiness',
            },
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type',
            },
        ),
    ]
