# Generated by Django 3.2.10 on 2022-09-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heads', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'heads',
            },
        ),
    ]
