# Generated by Django 3.2.10 on 2022-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20220922_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='fmv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
