# Generated by Django 3.2.10 on 2022-09-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='items',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='bussiness',
            table='tharun',
        ),
    ]
