# Generated by Django 3.2.10 on 2022-09-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20220908_1624'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bussiness',
            table='bussiness',
        ),
    ]
