# Generated by Django 3.2.10 on 2022-09-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_alter_bussiness_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='id',
            new_name='tid',
        ),
    ]
