# Generated by Django 3.2.10 on 2022-09-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_rename_id_type_tid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educational',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=450)),
                ('percentage', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'educational',
            },
        ),
    ]
