# Generated by Django 3.2.10 on 2022-09-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_educational'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.RemoveField(
            model_name='bussiness',
            name='items',
        ),
    ]
