# Generated by Django 3.2.10 on 2022-09-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_auto_20220916_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('assessment_year', models.CharField(default=True, max_length=45, null=True)),
                ('dor', models.DateField()),
                ('income', models.CharField(max_length=45)),
                ('taxpaid', models.EmailField(max_length=45)),
            ],
            options={
                'db_table': 'networth',
            },
        ),
    ]
