# Generated by Django 3.2.10 on 2022-09-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_networth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=4500)),
                ('email', models.CharField(max_length=45)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('board', models.CharField(blank=True, max_length=450, null=True)),
                ('percentage', models.CharField(blank=True, max_length=45, null=True)),
                ('cibil', models.CharField(max_length=45)),
                ('rbi', models.CharField(max_length=45)),
                ('assessment_year', models.CharField(max_length=45)),
                ('dor', models.DateField(blank=True, null=True)),
                ('income', models.CharField(blank=True, max_length=45, null=True)),
                ('taxpaid', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.AlterField(
            model_name='educational',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='networth',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
