# Generated by Django 3.2.10 on 2022-09-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_auto_20220916_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=45)),
                ('default', models.CharField(max_length=15)),
                ('u_of_measurement', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
                ('UOM', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=45)),
                ('measure', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'uom',
            },
        ),
        migrations.AlterField(
            model_name='persons',
            name='assessment_year',
            field=models.CharField(default=0, max_length=45),
        ),
    ]
