# Generated by Django 3.2.10 on 2022-09-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_auto_20220916_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='default',
            new_name='defaults',
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
