# Generated by Django 3.2.10 on 2022-09-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_auto_20220916_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='uom',
            old_name='family_name',
            new_name='name',
        ),
    ]
